# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XHOSRy4lTsbIVi8-GoBEHQxVJ3yD-1x
"""

# Commented out IPython magic to ensure Python compatibility.
# Подключение библиотек
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Настройка отображения графиков
# %matplotlib inline
plt.style.use('ggplot')

# Загрузка датасета
df = pd.read_csv('/content/sample_data/train.csv')

# Первый взгляд на данные
df.head()

# Количество строк и столбцов
print("Размер датасета (строки, столбцы):", df.shape)

# Названия всех столбцов
print("\nСтолбцы:")
print(df.columns.tolist())

# Типы данных столбцов
print("\nТипы данных:")
print(df.dtypes)

# Общая информация
df.info()

# 1. Количество пассажиров каждого класса
print("Пассажиры по классам:")
print(df['Pclass'].value_counts().sort_index())

# 2. Количество мужчин и женщин
print("\nПассажиры по полу:")
print(df['Sex'].value_counts())

# 3. Разделение на возрастные группы
bins = [0, 12, 18, 30, 50, 100]
labels = ['Дети (0-12)', 'Подростки (13-18)', 'Молодые (19-30)',
          'Взрослые (31-50)', 'Пожилые (50+)']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)
print("\nВозрастные группы:")
print(df['AgeGroup'].value_counts().sort_index())

# 4. Средний возраст
print("\nСредний возраст пассажиров:", round(df['Age'].mean(), 2))

# 5. Медианный возраст
print("Медианный возраст:", df['Age'].median())

# 6. Средняя стоимость билета
print("Средняя стоимость билета:", round(df['Fare'].mean(), 2))

# 1. Средняя стоимость билета по классам
print("Средняя стоимость билета по классам:")
print(df.groupby('Pclass')['Fare'].mean().round(2))

# 2. Средний возраст по классам
print("\nСредний возраст по классам:")
print(df.groupby('Pclass')['Age'].mean().round(2))

# 3. Количество мужчин и женщин в каждом классе
print("\nПол по классам:")
print(df.groupby(['Pclass', 'Sex']).size().unstack())

# 4. В каком классе больше всего пассажиров
print("\nСамый многочисленный класс:",
      df['Pclass'].value_counts().idxmax())

# 5. Самый дорогой билет
max_fare_row = df.loc[df['Fare'].idxmax()]
print("\nСамый дорогой билет:")
print(max_fare_row[['Name', 'Pclass', 'Age', 'Sex', 'Fare', 'Survived']])

# 1. Общее количество выживших и погибших
print("Выживаемость (0 - погиб, 1 - выжил):")
print(df['Survived'].value_counts())
print("Доля выживших:", round(df['Survived'].mean() * 100, 2), "%")

# 2. Выживаемость по полу
print("\nВыживаемость по полу:")
print(df.groupby('Sex')['Survived'].mean().round(3) * 100)

# 3. Выживаемость по полу и классу
print("\nВыживаемость по классу и полу (%):")
print((df.groupby(['Pclass', 'Sex'])['Survived'].mean() * 100).round(1))

# 4. Группа с наибольшей долей выживших
surv_by_group = df.groupby(['Pclass', 'Sex'])['Survived'].mean()
best_group = surv_by_group.idxmax()
print("\nГруппа с наибольшей долей выживших:", best_group,
      "—", round(surv_by_group.max() * 100, 1), "%")

# 1. График количества пассажиров по классам
plt.figure(figsize=(8, 5))
df['Pclass'].value_counts().sort_index().plot(kind='bar', color='steelblue')
plt.title('Количество пассажиров по классам')
plt.xlabel('Класс')
plt.ylabel('Количество пассажиров')
plt.xticks(rotation=0)
plt.show()

# 2. График выживаемости по полу
plt.figure(figsize=(8, 5))
df.groupby('Sex')['Survived'].mean().plot(kind='bar', color=['salmon', 'skyblue'])
plt.title('Доля выживших по полу')
plt.xlabel('Пол')
plt.ylabel('Доля выживших')
plt.xticks(rotation=0)
plt.show()

# Дополнительно: выживаемость по классу и полу
plt.figure(figsize=(8, 5))
df.groupby(['Pclass', 'Sex'])['Survived'].mean().unstack().plot(kind='bar')
plt.title('Выживаемость по классу и полу')
plt.xlabel('Класс')
plt.ylabel('Доля выживших')
plt.xticks(rotation=0)
plt.legend(title='Пол')
plt.show()

# Создаём признак "FamilySize"
df['FamilySize'] = df['SibSp'] + df['Parch']

# Выживаемость в зависимости от размера семьи
print("Выживаемость по размеру семьи:")
print(df.groupby('FamilySize')['Survived'].agg(['mean', 'count']).round(3))

# Визуализация
plt.figure(figsize=(8, 5))
df.groupby('FamilySize')['Survived'].mean().plot(kind='bar', color='teal')
plt.title('Доля выживших в зависимости от размера семьи')
plt.xlabel('Размер семьи (SibSp + Parch)')
plt.ylabel('Доля выживших')
plt.xticks(rotation=0)
plt.show()